class UserObject(dict):
    def __init__(s):
        object = {
            "type": "menu",
            "id": "DBORA",
            "tablecondition": "DBORAMISC",
            "icon": "database",
            "label": "Oracle Database",
            "menuwidth": 150,
            "itemswidth": 200,
            "items" : [
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "Summary",
                    "items": [
                        { "type": "menuitem", "label": "DB CPU & Wait", "action": "dispchart", "chart": "DBORASUM", "keyfunc": "G" },
                        { "type": "menuitem", "label": "DB CPU & Wait Classes", "action": "dispchart", "chart": "DBORASUMWC" },
                        { "type": "menuitem", "label": "DB CPU & Wait Classes (Percentage)", "action": "dispchart", "chart": "DBORASUMWCP" },
                        { "type": "menuitem", "label": "DB CPU & Wait Events", "action": "dispchart", "chart": "DBORASUMWE" },
                        { "type": "menuitem", "label": "DB Time Model", "action": "dispchart", "chart": "DBORASUME" },
                    ]
                },
                { "type": "separator"},
                { "type": "menuitem", "label": "System statistics", "action": "dispchart", "chart": "DBORASYS", "keycode": 38 },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "Wait events",
                    "items": [
                        { "type": "menuitem", "label": "Top wait events", "action": "dispchart", "chart": "DBORAWEV", "keyfunc": "W" },
                        { "type": "menuitem", "label": "Top wait events (Percentage)", "action": "dispchart", "chart": "DBORAWEVP"},
                        { "type": "menuitem", "label": "Top background wait events", "action": "dispchart", "chart": "DBORAWEB" },
                        { "type": "menuitem", "label": "Top wait events - Parallel query", "action": "dispchart", "chart": "DBORAWEP" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Choose wait event ...", "action": "dispchoice", "choice": "DBORAWEV" },
                        { "type": "menuitem", "label": "Choose background wait event ...", "action": "dispchoice", "choice": "DBORAWEB" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "Statistics",
                    "items": [
                        { "type": "menuitem", "label": "Logons", "action": "dispchart", "chart": "DBORALOGONS" },
                        { "type": "menuitem", "label": "User & Recursive calls", "action": "dispchart", "chart": "DBORACAL" },
                        { "type": "menuitem", "label": "Transactional activity", "action": "dispchart", "chart": "DBORACOM" },
                        { "type": "menuitem", "label": "SQL activity - Parsing", "action": "dispchart", "chart": "DBORAPRS" },
                        { "type": "menuitem", "label": "CPU usage", "action": "dispchart", "chart": "DBORACPU" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Sorts", "action": "dispchart", "chart": "DBORASORT" },
                        { "type": "menuitem", "label": "Read rows", "action": "dispchart", "chart": "DBORAROWS" },
                        { "type": "menuitem", "label": "Table scans", "action": "dispchart", "chart": "DBORASCAN" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Logical & physical reads", "action": "dispchart", "chart": "DBORAPHR" },
                        { "type": "menuitem", "label": "Logical & physical writes", "action": "dispchart", "chart": "DBORACHG" },
                        { "type": "menuitem", "label": "Default cache activity - Hit ratio", "action": "dispchart", "chart": "DBORAHITD" },
                        { "type": "menuitem", "label": "Keep cache activity - Hit ratio", "action": "dispchart", "chart": "DBORAHITK" },
                        { "type": "menuitem", "label": "Recycle cache activity - Hit ratio", "action": "dispchart", "chart": "DBORAHITR" },
                        { "type": "menuitem", "label": "IO overall activity", "action": "dispchart", "chart": "DBORAIOA" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "SQL*Net traffic", "action": "dispchart", "chart": "DBORASQLNET" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Choose statistic ...", "action": "dispchoice", "choice": "DBORASTA" },
                    ]
                },
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "Redo activity",
                    "items": [
                        { "type": "menuitem", "label": "General redo activity", "action": "dispchart", "chart": "DBORARDO" },
                        { "type": "menuitem", "label": "Wait & Write time per operation", "action": "dispchart", "chart": "DBORARDOT" },
                        { "type": "menuitem", "label": "Redo writes & size per write", "action": "dispchart", "chart": "DBORARDOW" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "Advisors",
                    "items": [
                        { "type": "menuitem", "label": "Default buffer pool", "action": "dispchart", "chart": "DBORABPAD" },
                        { "type": "menuitem", "label": "Keep buffer pool", "action": "dispchart", "chart": "DBORABPAK" },
                        { "type": "menuitem", "label": "Recycle buffer pool", "action": "dispchart", "chart": "DBORABPAR" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "SQL requests",
                    "items": [
                        { "type": "menuitem", "label": "SQL overview", "action": "displayout", "layout": "DBORASQL" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Top SQL by Elapsed time", "action": "dispchart", "chart": "DBORASQE" },
                        { "type": "menuitem", "label": "Top SQL by CPU time", "action": "dispchart", "chart": "DBORASQC" },
                        { "type": "menuitem", "label": "Top SQL by Gets", "action": "dispchart", "chart": "DBORASQG" },
                        { "type": "menuitem", "label": "Top SQL by Reads", "action": "dispchart", "chart": "DBORASQR" },
                        { "type": "menuitem", "label": "Top SQL by Executions", "action": "dispchart", "chart": "DBORASQX" },
                        { "type": "menuitem", "label": "Top SQL by Parse calls", "action": "dispchart", "chart": "DBORASQP" },
                        { "type": "menuitem", "label": "Top SQL by Sharable memory", "action": "dispchart", "chart": "DBORASQM" },
                        { "type": "menuitem", "label": "Top SQL by Version count", "action": "dispchart", "chart": "DBORASQV" },
                        { "type": "menuitem", "label": "Top SQL by Cluster wait time", "action": "dispchart", "chart": "DBORASQW" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 300,
                    "label": "Tablespaces & Files",
                    "items": [
                        { "type": "menuitem", "label": "Tablespace reads", "action": "dispchart", "chart": "DBORATBSR" },
                        { "type": "menuitem", "label": "Tablespace writes", "action": "dispchart", "chart": "DBORATBSW" },
                        { "type": "menuitem", "label": "Tablespace read times", "action": "dispchart", "chart": "DBORATBSRT" },
                        { "type": "menuitem", "label": "Tablespace buffer busy wait times", "action": "dispchart", "chart": "DBORATBSB" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Choose tablespace, read activity ...", "action": "dispchoice", "choice": "DBORATBS" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Database file reads", "action": "dispchart", "chart": "DBORAFILR" },
                        { "type": "menuitem", "label": "Database file writes", "action": "dispchart", "chart": "DBORAFILW" },
                        { "type": "menuitem", "label": "Database file read times", "action": "dispchart", "chart": "DBORAFILRT" },
                        { "type": "menuitem", "label": "Database file buffer busy wait times", "action": "dispchart", "chart": "DBORAFILB" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Choose database file, read activity ...", "action": "dispchoice", "choice": "DBORAFIL" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 330,
                    "label": "Segments",
                    "items": [
                        { "type": "menuitem", "label": "Top segments by logical reads", "action": "dispchart", "chart": "DBORASGLR" },
                        { "type": "menuitem", "label": "Top segments by physical reads", "action": "dispchart", "chart": "DBORASGPR" },
                        { "type": "menuitem", "label": "Top segments by physical read requests", "action": "dispchart", "chart": "DBORASGPRR" },
                        { "type": "menuitem", "label": "Top segments by unoptimized reads", "action": "dispchart", "chart": "DBORASGUR" },
                        { "type": "menuitem", "label": "Top segments by optimized reads", "action": "dispchart", "chart": "DBORASGOR" },
                        { "type": "menuitem", "label": "Top segments by direct physical reads", "action": "dispchart", "chart": "DBORASGDPR" },
                        { "type": "menuitem", "label": "Top segments by physical writes", "action": "dispchart", "chart": "DBORASGPW" },
                        { "type": "menuitem", "label": "Top segments by physical write requests", "action": "dispchart", "chart": "DBORASGPWR" },
                        { "type": "menuitem", "label": "Top segments by direct physical writes", "action": "dispchart", "chart": "DBORASGDPW" },
                        { "type": "menuitem", "label": "Top segments by table scans", "action": "dispchart", "chart": "DBORASGTS" },
                        { "type": "menuitem", "label": "Top segments by DB blocks changes", "action": "dispchart", "chart": "DBORASGDBC" },
                        { "type": "menuitem", "label": "Top segments by row lock waits", "action": "dispchart", "chart": "DBORASGRLW" },
                        { "type": "menuitem", "label": "Top segments by ITL waits", "action": "dispchart", "chart": "DBORASGIW" },
                        { "type": "menuitem", "label": "Top segments by buffer busy waits", "action": "dispchart", "chart": "DBORASGBBW" },
                        { "type": "menuitem", "label": "Top segments by global cache buffer busy", "action": "dispchart", "chart": "DBORASGGCBB" },
                        { "type": "menuitem", "label": "Top segments by CR blocks received", "action": "dispchart", "chart": "DBORASGCRBR" },
                        { "type": "menuitem", "label": "Top segments by Current blocks received", "action": "dispchart", "chart": "DBORASGCBR" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 320,
                    "label": "Services",
                    "items": [
                        { "type": "menuitem", "label": "Services - DB Time", "action": "dispchart", "chart": "DBORASVDBT" },
                        { "type": "menuitem", "label": "Services - DB CPU", "action": "dispchart", "chart": "DBORASVCPU" },
                        { "type": "menuitem", "label": "Services - Logical reads", "action": "dispchart", "chart": "DBORASVLR" },
                        { "type": "menuitem", "label": "Services - Physical reads", "action": "dispchart", "chart": "DBORASVPR" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Services - Time waited - User I/O", "action": "dispchart", "chart": "DBORASVUIO" },
                        { "type": "menuitem", "label": "Services - Time waited - Concurrency", "action": "dispchart", "chart": "DBORASVCON" },
                        { "type": "menuitem", "label": "Services - Time waited - Administrative", "action": "dispchart", "chart": "DBORASVADM" },
                        { "type": "menuitem", "label": "Services - Time waited - Network", "action": "dispchart", "chart": "DBORASVNET" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Choose service ...", "action": "dispchoice", "choice": "DBORASV" },
                    ]
                },
                { "type": "separator"},
                {
                    "type": "submenu",
                    "itemswidth": 200,
                    "label": "SGA usage",
                    "items": [
                        { "type": "menuitem", "label": "SGA usage", "action": "dispchart", "chart": "DBORASGA" },
                        { "type": "menuitem", "label": "Shared Pool usage", "action": "dispchart", "chart": "DBORASGAS" },
                        { "type": "menuitem", "label": "Large Pool usage", "action": "dispchart", "chart": "DBORASGAL" },
                        { "type": "menuitem", "label": "Java Pool usage", "action": "dispchart", "chart": "DBORASGAJ" },
                        { "type": "separator"},
                        { "type": "menuitem", "label": "Choose SGA part ...", "action": "dispchoice", "choice": "DBORASGA" },
                    ]
                },
                { "type": "menuitem", "label": "PGA usage", "action": "dispchart", "chart": "DBORAPGA" },
                {
                    "type": "submenu",
                    "itemswidth": 200,
                    "label": "Library cache",
                    "items": [
                        { "type": "menuitem", "label": "Reloads", "action": "dispchart", "chart": "DBORALIBR" },
                        { "type": "menuitem", "label": "Invalidations", "action": "dispchart", "chart": "DBORALIBI" },
                    ]
                },
                { "type": "separator", "tablecondition": "ORAHQS"},
                {
                    "type": "submenu",
                    "tablecondition": "ORAHQS",
                    "label": "History",
                    "itemswidth": 250,
                    "items" : [
                        {
                            "type": "submenu",
                            "itemswidth": 270,
                            "label": "SQL History",
                            "items": [
                                { "type": "menuitem", "label": "Top SQL by Elapsed time", "action": "dispchart", "chart": "DBORAHSQLE" },
                                { "type": "menuitem", "label": "Top SQL by CPU time", "action": "dispchart", "chart": "DBORAHSQLC" },
                                { "type": "menuitem", "label": "Top SQL by Waits - IO", "action": "dispchart", "chart": "DBORAHSQLWI" },
                                { "type": "menuitem", "label": "Top SQL by Waits - Application", "action": "dispchart", "chart": "DBORAHSQLWA" },
                                { "type": "menuitem", "label": "Top SQL by Waits - Concurrency", "action": "dispchart", "chart": "DBORAHSQLWC" },
                                { "type": "menuitem", "label": "Top SQL by Waits - Cluster", "action": "dispchart", "chart": "DBORAHSQLWR" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose SQL - Time statistic / sec", "action": "dispchoice", "choice": "DBORAHSQLTS0" },
                                { "type": "menuitem", "label": "Choose SQL - Time statistic / exec", "action": "dispchoice", "choice": "DBORAHSQLTX0" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Top SQL by Gets", "action": "dispchart", "chart": "DBORAHSQLG" },
                                { "type": "menuitem", "label": "Top SQL by Reads", "action": "dispchart", "chart": "DBORAHSQLR" },
                                { "type": "menuitem", "label": "Top SQL by Executions", "action": "dispchart", "chart": "DBORAHSQLX" },
                                { "type": "menuitem", "label": "Top SQL by Rows processed", "action": "dispchart", "chart": "DBORAHSQLN" },
                                { "type": "menuitem", "label": "Top SQL by Fetches operations", "action": "dispchart", "chart": "DBORAHSQLF" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose SQL - Statistics / sec", "action": "dispchoice", "choice": "DBORAHSQLSS0" },
                                { "type": "menuitem", "label": "Choose SQL - Statistics / exec", "action": "dispchoice", "choice": "DBORAHSQLSX0" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Top SQL by Parse calls", "action": "dispchart", "chart": "DBORAHSQLP" },
                                { "type": "menuitem", "label": "Top SQL by Invalidations", "action": "dispchart", "chart": "DBORAHSQLI" },
                                { "type": "menuitem", "label": "Top SQL by Loads", "action": "dispchart", "chart": "DBORAHSQLL" },
                                { "type": "menuitem", "label": "Top SQL by Sorts", "action": "dispchart", "chart": "DBORAHSQLS" },
                                { "type": "menuitem", "label": "Top SQL by Version count", "action": "dispchart", "chart": "DBORAHSQLV" },
                                { "type": "menuitem", "label": "Top SQL by Sharable memory", "action": "dispchart", "chart": "DBORAHSQLM" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose SQL - All statistics / sec", "action": "dispchoice", "choice": "DBORAHSQLAS0" },
                                { "type": "menuitem", "label": "Choose SQL - All statistics / exec", "action": "dispchoice", "choice": "DBORAHSQLAX0" },
                            ]
                        },
                        {
                            "type": "submenu",
                            "itemswidth": 270,
                            "label": "Plan Hash Value History",
                            "items": [
                                { "type": "menuitem", "label": "Top PHV by Elapsed time", "action": "dispchart", "chart": "DBORAHPHVE" },
                                { "type": "menuitem", "label": "Top PHV by CPU time", "action": "dispchart", "chart": "DBORAHPHVC" },
                                { "type": "menuitem", "label": "Top PHV by Waits - IO", "action": "dispchart", "chart": "DBORAHPHVWI" },
                                { "type": "menuitem", "label": "Top PHV by Waits - Application", "action": "dispchart", "chart": "DBORAHPHVWA" },
                                { "type": "menuitem", "label": "Top PHV by Waits - Concurrency", "action": "dispchart", "chart": "DBORAHPHVWC" },
                                { "type": "menuitem", "label": "Top PHV by Waits - Cluster", "action": "dispchart", "chart": "DBORAHPHVWR" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose PHV - Time statistic / sec", "action": "dispchoice", "choice": "DBORAHPHVTS0" },
                                { "type": "menuitem", "label": "Choose PHV - Time statistic / exec", "action": "dispchoice", "choice": "DBORAHPHVTX0" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Top PHV by Gets", "action": "dispchart", "chart": "DBORAHPHVG" },
                                { "type": "menuitem", "label": "Top PHV by Reads", "action": "dispchart", "chart": "DBORAHPHVR" },
                                { "type": "menuitem", "label": "Top PHV by Executions", "action": "dispchart", "chart": "DBORAHPHVX" },
                                { "type": "menuitem", "label": "Top PHV by Rows processed", "action": "dispchart", "chart": "DBORAHPHVN" },
                                { "type": "menuitem", "label": "Top PHV by Fetches operations", "action": "dispchart", "chart": "DBORAHPHVF" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose PHV - Statistics / sec", "action": "dispchoice", "choice": "DBORAHPHVSS0" },
                                { "type": "menuitem", "label": "Choose PHV - Statistics / exec", "action": "dispchoice", "choice": "DBORAHPHVSX0" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Top PHV by Parse calls", "action": "dispchart", "chart": "DBORAHPHVP" },
                                { "type": "menuitem", "label": "Top PHV by Invalidations", "action": "dispchart", "chart": "DBORAHPHVI" },
                                { "type": "menuitem", "label": "Top PHV by Loads", "action": "dispchart", "chart": "DBORAHPHVL" },
                                { "type": "menuitem", "label": "Top PHV by Sorts", "action": "dispchart", "chart": "DBORAHPHVS" },
                                { "type": "menuitem", "label": "Top PHV by Version count", "action": "dispchart", "chart": "DBORAHPHVV" },
                                { "type": "menuitem", "label": "Top PHV by Sharable memory", "action": "dispchart", "chart": "DBORAHPHVM" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose PHV - All statistics / sec", "action": "dispchoice", "choice": "DBORAHPHVAS0" },
                                { "type": "menuitem", "label": "Choose PHV - All statistics / exec", "action": "dispchoice", "choice": "DBORAHPHVAX0" },
                            ]
                        },
                        {
                            "type": "submenu",
                            "itemswidth": 270,
                            "label": "Force Matching Signature History",
                            "items": [
                                { "type": "menuitem", "label": "Top FMS by Elapsed time", "action": "dispchart", "chart": "DBORAHFMSE" },
                                { "type": "menuitem", "label": "Top FMS by CPU time", "action": "dispchart", "chart": "DBORAHFMSC" },
                                { "type": "menuitem", "label": "Top FMS by Waits - IO", "action": "dispchart", "chart": "DBORAHFMSWI" },
                                { "type": "menuitem", "label": "Top FMS by Waits - Application", "action": "dispchart", "chart": "DBORAHFMSWA" },
                                { "type": "menuitem", "label": "Top FMS by Waits - Concurrency", "action": "dispchart", "chart": "DBORAHFMSWC" },
                                { "type": "menuitem", "label": "Top FMS by Waits - Cluster", "action": "dispchart", "chart": "DBORAHFMSWR" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose FMS - Time statistic / sec", "action": "dispchoice", "choice": "DBORAHFMSTS0" },
                                { "type": "menuitem", "label": "Choose FMS - Time statistic / exec", "action": "dispchoice", "choice": "DBORAHFMSTX0" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Top FMS by Gets", "action": "dispchart", "chart": "DBORAHFMSG" },
                                { "type": "menuitem", "label": "Top FMS by Reads", "action": "dispchart", "chart": "DBORAHFMSR" },
                                { "type": "menuitem", "label": "Top FMS by Executions", "action": "dispchart", "chart": "DBORAHFMSX" },
                                { "type": "menuitem", "label": "Top FMS by Rows processed", "action": "dispchart", "chart": "DBORAHFMSN" },
                                { "type": "menuitem", "label": "Top FMS by Fetches operations", "action": "dispchart", "chart": "DBORAHFMSF" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose FMS - Statistics / sec", "action": "dispchoice", "choice": "DBORAHFMSSS0" },
                                { "type": "menuitem", "label": "Choose FMS - Statistics / exec", "action": "dispchoice", "choice": "DBORAHFMSSX0" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Top FMS by Parse calls", "action": "dispchart", "chart": "DBORAHFMSP" },
                                { "type": "menuitem", "label": "Top FMS by Invalidations", "action": "dispchart", "chart": "DBORAHFMSI" },
                                { "type": "menuitem", "label": "Top FMS by Loads", "action": "dispchart", "chart": "DBORAHFMSL" },
                                { "type": "menuitem", "label": "Top FMS by Sorts", "action": "dispchart", "chart": "DBORAHFMSS" },
                                { "type": "menuitem", "label": "Top FMS by Version count", "action": "dispchart", "chart": "DBORAHFMSV" },
                                { "type": "menuitem", "label": "Top FMS by Sharable memory", "action": "dispchart", "chart": "DBORAHFMSM" },
                                { "type": "separator"},
                                { "type": "menuitem", "label": "Choose FMS - All statistics / sec", "action": "dispchoice", "choice": "DBORAHFMSAS0" },
                                { "type": "menuitem", "label": "Choose FMS - All statistics / exec", "action": "dispchoice", "choice": "DBORAHFMSAX0" },
                            ]
                        },
                    ]
                },
                { "type": "separator", "tablecondition": "ORAHAS"},
                {
                    "type": "submenu",
                    "tablecondition": "ORAHAS",
                    "label": "ASH",
                    "itemswidth": 200,
                    "items" : [
                        {
                            "type": "submenu",
                            "itemswidth": 270,
                            "label": "DB Time overview",
                            "items": [
                                { "type": "menuitem", "label": "DB Time", "action": "dispchart", "chart": "DBORAASHDBTIME" },
                                { "type": "menuitem", "label": "Background DB Time", "action": "dispchart", "chart": "DBORAASHBDBTIME" },
                                { "type": "menuitem", "label": "Foreground & Background DB Time", "action": "dispchart", "chart": "DBORAASHOV" },
                            ]
                        },
                        { "type": "separator"},
                        {
                            "type": "submenu",
                            "itemswidth": 250,
                            "label": "Wait events",
                            "items": [
                                { "type": "menuitem", "label": " Top foreground wait classes", "action": "dispchart", "chart": "DBORAASHWEC" },
                                { "type": "menuitem", "label": " Top foreground wait events", "action": "dispchart", "chart": "DBORAASHWEV" },
                                { "type": "menuitem", "label": " Top background wait events", "action": "dispchart", "chart": "DBORAASHWEB" },
                                { "type": "separator"},
                                { "type": "submenu", "itemswidth": 250, "label": " Choose event ...",
                                    "items": [
                                        { "type": "menuitem", "label": " Top sessions", "action": "dispchoice", "choice": "DBORAASHWEVSES" },
                                        { "type": "menuitem", "label": " Top SQL requests", "action": "dispchoice", "choice": "DBORAASHWEVSQL" },
                                        { "type": "menuitem", "label": " Top SQL operations", "action": "dispchoice", "choice": "DBORAASHWEVOPN" },
                                    ]
                                },
                            ]
                        },
                        { "type": "separator"},
                        {
                            "type": "submenu",
                            "itemswidth": 300,
                            "label": "Sessions",
                            "items": [
                                { "type": "menuitem", "label": " Top foreground sessions", "action": "dispchart", "chart": "DBORAASHSES" },
                                { "type": "menuitem", "label": " Top blocked foreground sessions", "action": "dispchart", "chart": "DBORAASHBFSES" },
                                { "type": "menuitem", "label": " Top blocking sessions", "action": "dispchart", "chart": "DBORAASHHSES" },
                                { "type": "menuitem", "label": " Top background sessions", "action": "dispchart", "chart": "DBORAASHBSES" },
                                { "type": "menuitem", "label": " PGA allocated - Top sessions", "action": "dispchart", "chart": "DBORAASHPGA" },
                                { "type": "menuitem", "label": " Temp space allocated - Top sessions", "action": "dispchart", "chart": "DBORAASHTMP" },
                                { "type": "separator"},
                                { "type": "submenu", "itemswidth": 250, "label": " Choose session ...",
                                    "items": [
                                        { "type": "menuitem", "label": " Top wait events", "action": "dispchoice", "choice": "DBORAASHSESWEV" },
                                        { "type": "menuitem", "label": " Top SQL requests", "action": "dispchoice", "choice": "DBORAASHSESSQL" },
                                        { "type": "menuitem", "label": " Top SQL operations", "action": "dispchoice", "choice": "DBORAASHSESOPN" },
                                        { "type": "menuitem", "label": " PGA allocated", "action": "dispchoice", "choice": "DBORAASHSESPGA" },
                                        { "type": "menuitem", "label": " Temp space allocated", "action": "dispchoice", "choice": "DBORAASHSESTMP" },
                                    ]
                                },
                            ]
                        },
                        { "type": "separator"},
                        {
                            "type": "submenu",
                            "itemswidth": 300,
                            "label": "SQL requests",
                            "items": [
                                { "type": "menuitem", "label": " Top SQL requests", "action": "dispchart", "chart": "DBORAASHSQL" },
                                { "type": "menuitem", "label": " Top SQL requests on CPU", "action": "dispchart", "chart": "DBORAASHSQLCPU" },
                                { "type": "menuitem", "label": " Top waiting SQL requests", "action": "dispchart", "chart": "DBORAASHSQLWAIT" },
                                { "type": "menuitem", "label": " Top SQL operations", "action": "dispchart", "chart": "DBORAASHOPN" },
                                { "type": "menuitem", "label": " PGA allocated - Top SQL requests", "action": "dispchart", "chart": "DBORAASHPGA2" },
                                { "type": "menuitem", "label": " Temp space allocated - Top SQL requests", "action": "dispchart", "chart": "DBORAASHTMP2" },
                                { "type": "separator"},
                                { "type": "submenu", "itemswidth": 250, "label": " Choose SQL request ...",
                                    "items": [
                                        { "type": "menuitem", "label": " Top wait events", "action": "dispchoice", "choice": "DBORAASHSQLWEV" },
                                        { "type": "menuitem", "label": " Top sessions", "action": "dispchoice", "choice": "DBORAASHSQLSES" },
                                        { "type": "menuitem", "label": " Top sql plan hash values", "action": "dispchoice", "choice": "DBORAASHSQLPHV" },
                                        { "type": "menuitem", "label": " Top execution plan operations", "action": "dispchoice", "choice": "DBORAASHSQLEPO" },
                                        { "type": "menuitem", "label": " Top execute IDs", "action": "dispchoice", "choice": "DBORAASHSQLXID" },
                                        { "type": "menuitem", "label": " PGA allocated", "action": "dispchoice", "choice": "DBORAASHSQLPGA" },
                                        { "type": "menuitem", "label": " Temp space allocated", "action": "dispchoice", "choice": "DBORAASHSQLTMP" },
                                    ]
                                },
                            ]
                        },
                        { "type": "separator"},
                        {
                            "type": "submenu",
                            "itemswidth": 300,
                            "label": "Modules",
                            "items": [
                                { "type": "menuitem", "label": " Top modules", "action": "dispchart", "chart": "DBORAASHMOD" },
                                { "type": "separator"},
                                { "type": "submenu", "itemswidth": 250, "label": " Choose module ...",
                                    "items": [
                                        { "type": "menuitem", "label": " Top wait events", "action": "dispchoice", "choice": "DBORAASHMODWEV" },
                                        { "type": "menuitem", "label": " Top sessions", "action": "dispchoice", "choice": "DBORAASHMODSES" },
                                        { "type": "menuitem", "label": " Top SQL requests", "action": "dispchoice", "choice": "DBORAASHMODSQL" },
                                    ]
                                },
                            ]
                        },
                        { "type": "separator"},
                        {
                            "type": "submenu",
                            "itemswidth": 300,
                            "label": "Programs",
                            "items": [
                                { "type": "menuitem", "label": " Top programs", "action": "dispchart", "chart": "DBORAASHPRG" },
                                { "type": "separator"},
                                { "type": "submenu", "itemswidth": 250, "label": " Choose program ...",
                                    "items": [
                                        { "type": "menuitem", "label": " Top wait events", "action": "dispchoice", "choice": "DBORAASHPRGWEV" },
                                        { "type": "menuitem", "label": " Top sessions", "action": "dispchoice", "choice": "DBORAASHPRGSES" },
                                        { "type": "menuitem", "label": " Top SQL requests", "action": "dispchoice", "choice": "DBORAASHPRGSQL" },
                                    ]
                                },
                            ]
                        },
                        { "type": "separator"},
                        {
                            "type": "submenu",
                            "itemswidth": 300,
                            "label": "Machines",
                            "items": [
                                { "type": "menuitem", "label": " Top machines", "action": "dispchart", "chart": "DBORAASHMAC" },
                            ]
                        },
                    ]
                }
            ]
        }
        super(UserObject, s).__init__(**object)
