class UserObject(dict):

# Oracle foreign data wrapper
    ID = 'ORACLE_STATSPACK'
    IPADDRESS = 'orcl'
    PORT = '1521'
    CONTAINER = 'orcl'
    INSTANCE = 'orcl'
    SCHEMA = 'perfstat'
    USER = 'perfstat'
    PASSWORD = 'perfstat'
    MINDATE = "select to_char(sysdate - 1, 'YYYYMMDDHH24MISS') as mindate from dual"
    MAXDATE = "select '20991231235959' as maxdate from dual"
    RETENTION = 60

    DEFS = {
        "iname": "iname as (select '" + INSTANCE + "' name from dual)",
        "mindate": "mindate as (" + MINDATE + ")",
        "maxdate": "maxdate as (" + MAXDATE + ")",
        "masterlist": "masterlist as (select dbid, instance_number, to_char(startup_time, 'YYYYMMDDHH24MISS') startup_time from " + SCHEMA + ".stats$database_instance, iname where instance_name = iname.name)",
        "deltas": "deltas as (select dbid, instance_number, to_char(startup_time, 'YYYYMMDDHH24MISS') startup_time, bid, eid, to_char(snap_time, 'YYYYMMDDHH24MISS')||'000' snap_time, round(((snap_time - prev_snap_time) * 1440 * 60), 0) elapsed from (select snap_time, first_value(snap_time) over (order by snap_time asc rows between 1 preceding and current row) prev_snap_time, first_value(snap_id) over (order by snap_time asc rows between 1 preceding and current row) bid, snap_id eid, first_value(dbid) over (order by snap_time asc rows between 1 preceding and current row) prev_dbid, dbid, first_value(instance_number) over (order by snap_time asc rows between 1 preceding and current row) prev_instance_number, instance_number, first_value(startup_time) over (order by snap_time asc rows between 1 preceding and current row) prev_startup_time, startup_time from " + SCHEMA + ".stats$snapshot, mindate, maxdate  where session_id=0 and snap_time >= mindate.mindate and snap_time < maxdate.maxdate) where dbid=prev_dbid and instance_number=prev_instance_number and startup_time=prev_startup_time and bid != eid )",
        "validdeltas": "validdeltas as (select d.dbid, d.instance_number, d.startup_time, d.bid, d.eid, d.snap_time, d.elapsed from deltas d, masterlist m where d.dbid = m.dbid and d.instance_number = m.instance_number and d.startup_time = m.startup_time)",
        "dborastatspack": "dborastatspack as (select 'statspack' type from dual)",
        "dboramisc": "dboramisc as (select snap_time timestamp, elapsed, elapsed avgelapsed, s.value sessions from validdeltas v, " + SCHEMA + ".stats$sysstat s where s.name = 'logons current' and v.eid = s.snap_id and v.instance_number = s.instance_number and v.dbid = s.dbid)",
        "dborainfo": "dborainfo as (select snap_time timestamp, startup_time startup from validdeltas)",
        "dboratms": "dboratms as (select v.snap_time timestamp, sn.stat_name statistic, (e.value - b.value) / v.elapsed / 1000000 time from validdeltas v, " + SCHEMA + ".stats$sys_time_model e, " + SCHEMA + ".stats$sys_time_model b, " + SCHEMA + ".stats$time_model_statname sn where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid  = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.stat_id = e.stat_id and sn.stat_id = e.stat_id and e.value - b.value > 0)",
        "dborawev": "dborawev as (select v.snap_time timestamp, e.event,(e.total_waits_fg - nvl(b.total_waits_fg,0)) / v.elapsed count, (e.total_timeouts_fg - nvl(b.total_timeouts_fg,0)) / v.elapsed timeouts, (e.time_waited_micro_fg - nvl(b.time_waited_micro_fg,0)) / v.elapsed / 1000000 time from validdeltas v, " + SCHEMA + ".stats$system_event b, " + SCHEMA + ".stats$system_event e, " + SCHEMA + ".stats$idle_event i where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.event = e.event and e.total_waits_fg > nvl(b.total_waits_fg,0) and i.event(+) = e.event)",
        "dboraweb": "dboraweb as (select v.snap_time timestamp, e.event, (e.total_waits - nvl(b.total_waits,0)) / v.elapsed count, (e.total_timeouts - nvl(b.total_timeouts,0)) / v.elapsed timeouts, (e.time_waited_micro - nvl(b.time_waited_micro,0)) / v.elapsed / 1000000 time from validdeltas v, " + SCHEMA + ".stats$bg_event_summary b, " + SCHEMA + ".stats$bg_event_summary e, " + SCHEMA + ".stats$idle_event i where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.event = e.event and e.total_waits > nvl(b.total_waits,0) and i.event(+) = e.event)",
        "dboraweh": "dboraweh as (select v.snap_time timestamp, n.event event, e.wait_time_milli*1024 bucket, (e.wait_count - nvl(b.wait_count, 0)) / v.elapsed count from validdeltas v, " + SCHEMA + ".stats$event_histogram b, " + SCHEMA + ".stats$event_histogram e, (select distinct event, event_id from " + SCHEMA + ".stats$system_event) n where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.event_id = e.event_id and b.wait_time_milli = e.wait_time_milli and e.event_id = n.event_id and e.wait_count - nvl(b.wait_count, 0) > 0)",
        "dborasqc": "dborasqc as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.cpu_time < b.cpu_time) then e.cpu_time / v.elapsed / 1000000 else (e.cpu_time - nvl(b.cpu_time,0)) / v.elapsed /1000000 end) cpu, sum(case when (e.address != b.address) or (e.elapsed_time < b.elapsed_time) then e.elapsed_time / v.elapsed / 1000000 else (e.elapsed_time - nvl(b.elapsed_time,0)) / v.elapsed / 1000000 end) elapsed, sum(case when (e.address != b.address) or (e.buffer_gets < b.buffer_gets) then e.buffer_gets / v.elapsed else (e.buffer_gets - nvl(b.buffer_gets,0)) / v.elapsed end) gets, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqe": "dborasqe as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.cpu_time < b.cpu_time) then e.cpu_time / v.elapsed / 1000000 else (e.cpu_time - nvl(b.cpu_time,0)) / v.elapsed /1000000 end) cpu, sum(case when (e.address != b.address) or (e.elapsed_time < b.elapsed_time) then e.elapsed_time / v.elapsed / 1000000 else (e.elapsed_time - nvl(b.elapsed_time,0)) / v.elapsed / 1000000 end) elapsed, sum(case when (e.address != b.address) or (e.disk_reads < b.disk_reads) then e.disk_reads / v.elapsed else (e.disk_reads - nvl(b.disk_reads,0)) / v.elapsed end) reads, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqg": "dborasqg as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.cpu_time < b.cpu_time) then e.cpu_time / v.elapsed / 1000000 else (e.cpu_time - nvl(b.cpu_time,0)) / v.elapsed /1000000 end) cpu, sum(case when (e.address != b.address) or (e.elapsed_time < b.elapsed_time) then e.elapsed_time / v.elapsed / 1000000 else (e.elapsed_time - nvl(b.elapsed_time,0)) / v.elapsed / 1000000 end) elapsed, sum(case when (e.address != b.address) or (e.buffer_gets < b.buffer_gets) then e.buffer_gets / v.elapsed else (e.buffer_gets - nvl(b.buffer_gets,0)) / v.elapsed end) gets, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqr": "dborasqr as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.cpu_time < b.cpu_time) then e.cpu_time / v.elapsed / 1000000 else (e.cpu_time - nvl(b.cpu_time,0)) / v.elapsed /1000000 end) cpu, sum(case when (e.address != b.address) or (e.elapsed_time < b.elapsed_time) then e.elapsed_time / v.elapsed / 1000000 else (e.elapsed_time - nvl(b.elapsed_time,0)) / v.elapsed / 1000000 end) elapsed, sum(case when (e.address != b.address) or (e.disk_reads < b.disk_reads) then e.disk_reads / v.elapsed else (e.disk_reads - nvl(b.disk_reads,0)) / v.elapsed end) reads, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqx": "dborasqx as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.rows_processed < b.rows_processed) then e.rows_processed / v.elapsed else (e.rows_processed - nvl(b.rows_processed,0)) / v.elapsed end) rowes, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqp": "dborasqp as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.parse_calls < b.parse_calls) then e.parse_calls / v.elapsed else (e.parse_calls - nvl(b.parse_calls,0)) / v.elapsed end) parses, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqm": "dborasqm as (select v.snap_time timestamp, e.sql_id sqlid, sum(e.sharable_mem) sharedmem, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqv": "dborasqv as (select v.snap_time timestamp, e.sql_id sqlid, sum(e.version_count) versioncount, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborasqw": "dborasqw as (select v.snap_time timestamp, e.sql_id sqlid, sum(case when (e.address != b.address) or (e.cpu_time < b.cpu_time) then e.cpu_time / v.elapsed / 1000000 else (e.cpu_time - nvl(b.cpu_time,0)) / v.elapsed /1000000 end) cpu, sum(case when (e.address != b.address) or (e.elapsed_time < b.elapsed_time) then e.elapsed_time / v.elapsed / 1000000 else (e.elapsed_time - nvl(b.elapsed_time,0)) / v.elapsed / 1000000 end) elapsed, sum(case when (e.address != b.address) or (e.cluster_wait_time < b.cluster_wait_time) then e.cluster_wait_time / v.elapsed / 1000000 else (e.cluster_wait_time - nvl(b.cluster_wait_time,0)) / v.elapsed / 1000000 end) clusterwait, sum(case when (e.address != b.address) or (e.executions < b.executions) then e.executions / v.elapsed else (e.executions - nvl(b.executions,0)) / v.elapsed end) execs from validdeltas v, " + SCHEMA + ".stats$sql_summary b, " + SCHEMA + ".stats$sql_summary e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.old_hash_value = e.old_hash_value and b.address = e.address group by v.snap_time, e.sql_id)",
        "dborareq": "dborareq as (select sql_id sqlid, rtrim(xmlagg(xmlelement(e,sql_text,'').extract('//text()') order by piece).GetClobVal(),',') as request from " + SCHEMA + ".stats$sqltext where old_hash_value in (select old_hash_value from validdeltas v, " + SCHEMA + ".stats$sql_summary e where e.snap_id = v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number) group by sql_id)",
        "dborasta": "dborasta as (select v.snap_time timestamp, b.name statistic, (e.value - nvl(b.value,0)) / v.elapsed value from validdeltas v, " + SCHEMA + ".stats$sysstat b, " + SCHEMA + ".stats$sysstat e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.name = e.name and e.name not in ('logons current', 'opened cursors current', 'workarea memory allocated', 'session cursor cache count') and e.value >= nvl(b.value,0) and e.value  >  0)",
        "dboradrv": "dboradrv as (select v.snap_time timestamp, 'log switches (derived)' statistic, (e.sequence# - b.sequence#) / v.elapsed value from validdeltas v, " + SCHEMA + ".stats$thread e, " + SCHEMA + ".stats$thread b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.thread# = e.thread# and b.thread_instance_number = e.thread_instance_number and e.thread_instance_number = v.instance_number)",
        "dboraoss": "dboraoss as (select v.snap_time timestamp, osn.stat_name statistic, decode( osn.cumulative, 'NO', e.value, e.value - b.value) value from validdeltas v, " + SCHEMA + ".stats$osstat b, " + SCHEMA + ".stats$osstat e, " + SCHEMA + ".stats$osstatname osn where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.osstat_id = e.osstat_id and osn.osstat_id = e.osstat_id and (osn.stat_name not like 'AVG_%' and osn.stat_name not like '%LOAD%') and e.value >= b.value and e.value > 0)",
        "dboratbs": "dboratbs as (select v.snap_time timestamp, e.tsname tablespace, sum ((e.phyrds - nvl(b.phyrds,0)) / v.elapsed) reads, sum ((e.phywrts - nvl(b.phywrts,0)) / v.elapsed) writes, sum ((e.wait_count - nvl(b.wait_count,0)) / v.elapsed) busy, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, sum(e.phyblkrd - nvl(b.phyblkrd,0)) / sum(e.phyrds - nvl(b.phyrds,0))) blocksperread, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, (sum(e.readtim - nvl(b.readtim,0)) / sum(e.phyrds  - nvl(b.phyrds,0)))*10) readtime, decode (sum(e.wait_count - nvl(b.wait_count, 0)), 0, 0, (sum(e.time - nvl(b.time,0)) / sum(e.wait_count - nvl(b.wait_count,0)))*10) busytime from validdeltas v, " + SCHEMA + ".stats$filestatxs e, " + SCHEMA + ".stats$filestatxs b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.tsname = e.tsname and b.filename = e.filename and ( (e.phyrds - nvl(b.phyrds,0)) + (e.phywrts - nvl(b.phywrts,0))) > 0 group by v.snap_time, e.tsname union all select v.snap_time timestamp, e.tsname tablespace, sum ((e.phyrds - nvl(b.phyrds,0)) / v.elapsed) reads, sum ((e.phywrts - nvl(b.phywrts,0)) / v.elapsed) writes, sum ((e.wait_count - nvl(b.wait_count,0)) / v.elapsed) busy, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, sum(e.phyblkrd - nvl(b.phyblkrd,0)) / sum(e.phyrds - nvl(b.phyrds,0))) blocksperread, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, (sum(e.readtim - nvl(b.readtim,0)) / sum(e.phyrds  - nvl(b.phyrds,0)))*10) readtime, decode (sum(e.wait_count - nvl(b.wait_count, 0)), 0, 0, (sum(e.time - nvl(b.time,0)) / sum(e.wait_count - nvl(b.wait_count,0)))*10) busytime from validdeltas v, " + SCHEMA + ".stats$tempstatxs e, " + SCHEMA + ".stats$tempstatxs b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.tsname = e.tsname and b.filename = e.filename and ((e.phyrds  - nvl(b.phyrds,0)) + (e.phywrts - nvl(b.phywrts,0))) > 0 group by v.snap_time, e.tsname)",
        "dborafil": "dborafil as (select v.snap_time timestamp, e.tsname tablespace, e.filename filex, sum ((e.phyrds - nvl(b.phyrds,0)) / v.elapsed) reads, sum ((e.phywrts - nvl(b.phywrts,0)) / v.elapsed) writes, sum ((e.wait_count - nvl(b.wait_count,0)) / v.elapsed) busy, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, sum(e.phyblkrd - nvl(b.phyblkrd,0)) / sum(e.phyrds - nvl(b.phyrds,0))) blocksperread, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, (sum(e.readtim - nvl(b.readtim,0)) / sum(e.phyrds  - nvl(b.phyrds,0)))*10) readtime, decode (sum(e.wait_count - nvl(b.wait_count, 0)), 0, 0, (sum(e.time - nvl(b.time,0)) / sum(e.wait_count - nvl(b.wait_count,0)))*10) busytime from validdeltas v, " + SCHEMA + ".stats$filestatxs e, " + SCHEMA + ".stats$filestatxs b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.tsname = e.tsname and b.filename = e.filename and ( (e.phyrds - nvl(b.phyrds,0)) + (e.phywrts - nvl(b.phywrts,0))) > 0 group by v.snap_time, e.tsname,e.filename union all select v.snap_time timestamp, e.tsname tablespace, e.filename filex, sum ((e.phyrds - nvl(b.phyrds,0)) / v.elapsed) reads, sum ((e.phywrts - nvl(b.phywrts,0)) / v.elapsed) writes, sum ((e.wait_count - nvl(b.wait_count,0)) / v.elapsed) busy, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, sum(e.phyblkrd - nvl(b.phyblkrd,0)) / sum(e.phyrds - nvl(b.phyrds,0))) blocksperread, decode( sum(e.phyrds - nvl(b.phyrds,0)), 0, 0, (sum(e.readtim - nvl(b.readtim,0)) / sum(e.phyrds  - nvl(b.phyrds,0)))*10) readtime, decode (sum(e.wait_count - nvl(b.wait_count, 0)), 0, 0, (sum(e.time - nvl(b.time,0)) / sum(e.wait_count - nvl(b.wait_count,0)))*10) busytime from validdeltas v, " + SCHEMA + ".stats$tempstatxs e, " + SCHEMA + ".stats$tempstatxs b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.tsname = e.tsname and b.filename = e.filename and ((e.phyrds  - nvl(b.phyrds,0)) + (e.phywrts - nvl(b.phywrts,0))) > 0 group by v.snap_time, e.tsname, e.filename)",
        "dboramdc": "dboramdc as (select v.snap_time timestamp, replace(replace(replace(e.component, 'DEFAULT ', 'D:'), 'KEEP ', 'K:'), 'RECYCLE','R:') component, substr(e.last_oper_type,1,6) || decode(e.last_oper_type, 'STATIC', ' ', '/') || substr(e.last_oper_mode,1,3) operation, e.current_size / 1048576 sizex, 0.0 vmin, 0.0 vmax, (e.oper_count - b.oper_count) / v.elapsed opcount from validdeltas v, " + SCHEMA + ".stats$memory_dynamic_comps b, " + SCHEMA + ".stats$memory_dynamic_comps e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.component = e.component and (e.current_size + b.current_size > 0 or e.oper_count - b.oper_count > 0))",
        "dborabuf": "dborabuf as (select v.snap_time timestamp, replace(e.block_size/1024||'k', p.value / 1024||'k', substr(e.name,1,1)) bufpool, (e.db_block_gets - nvl(b.db_block_gets,0) + e.consistent_gets  - nvl(b.consistent_gets,0)) / v.elapsed gets, (e.physical_reads - nvl(b.physical_reads,0)) / v.elapsed reads, (e.physical_writes - nvl(b.physical_writes,0)) / v.elapsed writes, (e.free_buffer_wait - nvl(b.free_buffer_wait,0)) / v.elapsed freewaits, (e.write_complete_wait - nvl(b.write_complete_wait,0)) / v.elapsed writecompletewaits, (e.buffer_busy_wait - nvl(b.buffer_busy_wait,0)) / v.elapsed busywaits from validdeltas v, " + SCHEMA + ".stats$buffer_pool_statistics b, " + SCHEMA + ".stats$buffer_pool_statistics e, " + SCHEMA + ".stats$parameter p where b.snap_id = v.bid and e.snap_id = v.eid and p.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and p.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and p.instance_number= v.instance_number and b.instance_number = e.instance_number and b.id = e.id and p.name='db_block_size')",
        "dboraenq": "dboraenq as (select v.snap_time timestamp, e.eq_type || '-' || to_char(nvl(l.name,' ')) || decode( upper(e.req_reason), 'CONTENTION', null, '-',  null, ' ('||e.req_reason||')') enqueue, (e.total_req# - nvl(b.total_req#,0)) / v.elapsed requests, (e.succ_req# - nvl(b.succ_req#,0)) / v.elapsed succgets, (e.failed_req# - nvl(b.failed_req#,0)) / v.elapsed failedgets, (e.total_wait# - nvl(b.total_wait#,0)) / v.elapsed waits, decode(  (e.total_wait#   - nvl(b.total_wait#,0)), 0, to_number(0), ( (e.cum_wait_time - nvl(b.cum_wait_time,0)) / (e.total_wait#   - nvl(b.total_wait#,0)))) awttm from validdeltas v, " + SCHEMA + ".stats$enqueue_statistics e, " + SCHEMA + ".stats$enqueue_statistics b, v$lock_type l where b.snap_id = v.bid and e.snap_id  = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.eq_type = e.eq_type and b.req_reason = e.req_reason and e.total_wait# - nvl(b.total_wait#,0) > 0 and l.type = e.eq_type)",
        "dboralaw": "dboralaw as (select v.snap_time timestamp, b.name latch, (e.wait_time - b.wait_time) / v.elapsed / 1000000 wait from validdeltas v, " + SCHEMA + ".stats$latch b, " + SCHEMA + ".stats$latch e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.name = e.name and (e.gets - b.gets + e.immediate_gets - b.immediate_gets) > 0)",
        "dboralat": "dboralat as (select v.snap_time timestamp, b.name latch , (e.gets - b.gets) / v.elapsed gets, (e.misses - b.misses) / v.elapsed misses, (e.sleeps - b.sleeps) / v.elapsed sleeps from validdeltas v, " + SCHEMA + ".stats$latch b, " + SCHEMA + ".stats$latch e where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.dbid = e.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.name = e.name and e.sleeps - b.sleeps > 0)",
        "dboralib": "dboralib as (select v.snap_time timestamp, e.namespace item, (e.gets - b.gets) / v.elapsed gets, (e.pins - b.pins) / v.elapsed pins, (e.reloads - b.reloads) / v.elapsed reloads, (e.invalidations - b.invalidations) / v.elapsed invalidations from validdeltas v, " + SCHEMA + ".stats$librarycache b, " + SCHEMA + ".stats$librarycache e where b.snap_id = v.bid and e.snap_id = v.eid and e.dbid = v.dbid and b.dbid = e.dbid and e.instance_number = v.instance_number and b.instance_number = e.instance_number and b.namespace = e.namespace and e.gets - b.gets > 0)",
        "dborasga": "dborasga as (select v.snap_time timestamp, pool, name, s.bytes/1024/1024 sizex from validdeltas v, " + SCHEMA + ".stats$sgastat s where s.snap_id = v.eid and s.dbid = v.dbid and s.instance_number = v.instance_number)",
        "dboraprm": "dboraprm as (select v.snap_time timestamp, e.name parameter, e.value value from validdeltas v, " + SCHEMA + ".stats$parameter e where e.snap_id = v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number and translate(e.name, '_', '#') not like '##%' and (nvl(e.isdefault, 'X') = 'FALSE' or nvl(e.ismodified,'X')  != 'FALSE'))",
        "dborasglr": "dborasglr as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.logical_reads / r.elapsed gets from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.logical_reads - nvl(b.logical_reads, 0) logical_reads from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.logical_reads - nvl(b.logical_reads, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasgpr": "dborasgpr as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.physical_reads / r.elapsed reads from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.physical_reads - nvl(b.physical_reads, 0) physical_reads from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.physical_reads - nvl(b.physical_reads, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasgrlw": "dborasgrlw as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.row_lock_waits / r.elapsed waits from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.row_lock_waits - nvl(b.row_lock_waits, 0) row_lock_waits from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.row_lock_waits - nvl(b.row_lock_waits, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasgiw": "dborasgiw as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.itl_waits / r.elapsed waits from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.itl_waits - nvl(b.itl_waits, 0) itl_waits from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.itl_waits - nvl(b.itl_waits, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasgbbw": "dborasgbbw as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.buffer_busy_waits / r.elapsed waits from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.buffer_busy_waits - nvl(b.buffer_busy_waits, 0) buffer_busy_waits from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.buffer_busy_waits - nvl(b.buffer_busy_waits, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasggcbb": "dborasggcbb as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.gc_buffer_busy / r.elapsed waits from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.gc_buffer_busy - nvl(b.gc_buffer_busy, 0) gc_buffer_busy from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.gc_buffer_busy - nvl(b.gc_buffer_busy, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasgcrbr": "dborasgcrbr as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.gc_cr_blocks_received / r.elapsed blocks from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.gc_cr_blocks_received - nvl(b.gc_cr_blocks_received, 0) gc_cr_blocks_received from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.gc_cr_blocks_received - nvl(b.gc_cr_blocks_received, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborasgcbr": "dborasgcbr as (select r.snap_time timestamp, n.owner owner, n.tablespace_name tablespace, n.object_name object, n.subobject_name subobject, n.object_type objtype, r.gc_current_blocks_received / r.elapsed blocks from " + SCHEMA + ".stats$seg_stat_obj n, (select * from (select v.snap_time, v.elapsed, e.dataobj#, e.obj#, e.ts#, e.dbid, e.gc_current_blocks_received - nvl(b.gc_current_blocks_received, 0) gc_current_blocks_received from validdeltas v, " + SCHEMA + ".stats$seg_stat e, " + SCHEMA + ".stats$seg_stat b where b.snap_id = v.bid and e.snap_id = v.eid and b.dbid = v.dbid and e.dbid = v.dbid and b.instance_number = v.instance_number and e.instance_number = v.instance_number and b.ts# = e.ts# and b.obj# = e.obj# and b.dataobj# = e.dataobj# and e.gc_current_blocks_received - nvl(b.gc_current_blocks_received, 0) > 0) d) r where n.dataobj# = r.dataobj# and n.obj# = r.obj# and n.ts# = r.ts# and n.dbid = r.dbid)",
        "dborapga": "dborapga as (select mu.snap_time timestamp, to_number(p.value)/1024/1024 aggrtarget, mu.pat/1024/1024 autotarget, mu.PGA_alloc/1024/1024 memalloc, (mu.PGA_used_auto + mu.PGA_used_man)/1024/1024 memused from (select v.snap_time, v.eid, v.dbid, v.instance_number, sum(case when name = 'total PGA allocated' then value else 0 end) PGA_alloc, sum(case when name = 'total PGA used for auto workareas' then value else 0 end) PGA_used_auto, sum(case when name = 'total PGA used for manual workareas' then value else 0 end) PGA_used_man, sum(case when name = 'global memory bound' then value else 0 end) glob_mem_bnd, sum(case when name = 'aggregate PGA auto target' then value else 0 end) pat from validdeltas v, " + SCHEMA + ".stats$pgastat pga where pga.snap_id = v.eid and pga.dbid = v.dbid and pga.instance_number = v.instance_number group by v.snap_time, v.eid, v.dbid, v.instance_number) mu, " + SCHEMA + ".stats$parameter p where p.snap_id = mu.eid and p.dbid = mu.dbid and p.instance_number = mu.instance_number and p.name = 'pga_aggregate_target' and p.value  != '0')",
        "dborapgc": "dborapgc as (select v.snap_time timestamp, case when e.high_optimal_size >= 1024*1024*1024*1024 then lpad(round(e.high_optimal_size/1024/1024/1024/1024) || 'T',7) when e.high_optimal_size >= 1024*1024*1024 then lpad(round(e.high_optimal_size/1024/1024/1024) || 'G',7) when e.high_optimal_size >= 1024*1024 then lpad(round(e.high_optimal_size/1024/1024) || 'M',7) when e.high_optimal_size >= 1024 then lpad(round(e.high_optimal_size/1024) || 'K',7) else e.high_optimal_size || 'B' end highoptimal, (e.total_executions - nvl(b.total_executions,0)) / v.elapsed totexecs, (e.optimal_executions - nvl(b.optimal_executions,0)) / v.elapsed execs0, (e.onepass_executions - nvl(b.onepass_executions,0)) / v.elapsed execs1, (e.multipasses_executions - nvl(b.multipasses_executions,0)) / v.elapsed execs2 from validdeltas v, " + SCHEMA + ".stats$sql_workarea_histogram e, " + SCHEMA + ".stats$sql_workarea_histogram b where e.snap_id = v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number and b.snap_id = v.bid and b.dbid = e.dbid and b.instance_number = e.instance_number and b.low_optimal_size = e.low_optimal_size and b.high_optimal_size = e.high_optimal_size and e.total_executions  - nvl(b.total_executions,0) > 0)",
        "dborabpa": "dborabpa as (select v.snap_time timestamp, e.name bufpool, e.size_factor sizefactor, e.estd_physical_read_factor estphysreadsfactor from validdeltas v, " + SCHEMA + ".stats$db_cache_advice e where e.snap_id =v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number and e.estd_physical_reads > 0)",
        "dborapma": "dborapma as (select v.snap_time timestamp, e.pga_target_factor sizefactor, e.estd_extra_bytes_rw  byt_rw, e.estd_overalloc_count eoc from validdeltas v, " + SCHEMA + ".stats$pga_target_advice e where e.snap_id = v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number)",
        "dboraspa": "dboraspa as (select v.snap_time timestamp, e.shared_pool_size_factor sizefactor, e.estd_lc_load_time_factor elcltf from validdeltas v, " + SCHEMA + ".stats$shared_pool_advice e where e.snap_id = v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number)",
        "dborasgaa": "dborasgaa as (select v.snap_time timestamp, e.sga_size_factor sizefactor, e.estd_physical_reads epr from validdeltas v, " + SCHEMA + ".stats$sga_target_advice e where e.snap_id = v.eid and e.dbid = v.dbid and e.instance_number = v.instance_number)",
        "orahas": "orahas as (select to_char(sample_time, 'YYYYMMDDHH24MISS')||'000' timepstamp, 1 kairos_count, sql_id, sample_id, session_id, session_serial#, user_id, sql_child_number, sql_plan_hash_value, force_matching_signature, sql_opcode, service_hash, decode(session_type, 'USER', 'FOREGROUND', session_type), session_state, qc_session_id, qc_instance_id, blocking_session, blocking_session_status, blocking_session_serial#, event, event_id, seq#, p1, p1text, p2, p2text, p3, p3text, wait_class, wait_class_id, nvl(wait_time,0), nvl(time_waited,0), rawtohex(xid), current_obj#, current_file#, current_block#, program, module, action, client_id, blocking_hangchain_info, blocking_inst_id, capture_overhead, consumer_group_id, current_row#, nvl(delta_interconnect_io_bytes,0), nvl(delta_read_io_bytes,0), nvl(delta_read_io_requests,0), nvl(delta_time,0), nvl(delta_write_io_bytes,0), nvl(delta_write_io_requests,0), ecid, flags, in_bind, in_connection_mgmt, in_cursor_close, in_hard_parse, in_java_execution, in_parse, in_plsql_compilation, in_plsql_execution, in_plsql_rpc, in_sequence_load, in_sql_execution, is_captured, is_replayed, is_sqlid_current, machine, nvl(pga_allocated,0), plsql_entry_object_id, plsql_entry_subprogram_id, plsql_object_id, plsql_subprogram_id, port, qc_session_serial#, remote_instance#, replay_overhead, sql_exec_id, to_char(sql_exec_start, 'YYYYMMDDHH24MISS'), sql_opname, sql_plan_line_id, sql_plan_operation, sql_plan_options, nvl(temp_space_allocated,0), time_model, nvl(tm_delta_cpu_time,0), nvl(tm_delta_db_time,0), nvl(tm_delta_time,0), top_level_call#, top_level_call_name, top_level_sql_id, top_level_sql_opcode, dbreplay_file_id, dbreplay_call_counter from mindate, maxdate, bash$hist_active_sess_history sq where snap_time between mindate.mindate and maxdate.maxdate)",
        "orahqt": "orahqt as (select sql_id, rtrim(xmlagg(xmlelement(e,sql_text,'').extract('//text()') order by piece).GetClobVal(),',') as sql_text from " + SCHEMA + ".stats$sqltext group by sql_id)",
    }

    def __init__(s):
        object = {
            "type": "liveobject",
            "id": UserObject.ID,
            "extension": "oracle_fdw",
            "options": "dbserver '//" + UserObject.IPADDRESS + ":" + UserObject.PORT + "/" + UserObject.CONTAINER + "'",
            "user": UserObject.USER,
            "password": UserObject.PASSWORD,
            "retention": UserObject.RETENTION,
            "tables": {
                "MASTERLIST": {
                    "request": "with %(iname)s, %(masterlist)s select * from masterlist" % UserObject.DEFS,
                    "description": {"dbid": "text", "instance_number": "text", "startup_time": "text"}
                },
                "DELTAS": {
                    "request": "with %(mindate)s, %(maxdate)s, %(deltas)s select * from deltas" % UserObject.DEFS,
                    "description": {"dbid": "text", "instance_number": "text", "startup_time": "text", "bid": "text", "eid": "text", "snap_time": "text", "elapsed": "bigint"}
                },
                "VALIDDELTAS": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s select * from validdeltas" % UserObject.DEFS,
                    "description": {"dbid": "text", "instance_number": "text", "startup_time": "text", "bid": "text", "eid": "text", "snap_time": "text", "elapsed": "bigint"}
                },
                "DBORASTATSPACK": {
                    "request": "with %(dborastatspack)s select * from dborastatspack" % UserObject.DEFS,
                    "description": {"type": "text"}
                },
                "DBORAMISC": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboramisc)s select * from dboramisc" % UserObject.DEFS,
                    "description": {"timestamp": "text", "elapsed": "bigint", "avgelapsed": "real", "sessions": "real", "type": "text"}
                },
                "DBORAINFO": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborainfo)s select * from dborainfo" % UserObject.DEFS,
                    "description": {"timestamp": "text", "startup": "text"}
                },
                "DBORATMS": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboratms)s select * from dboratms" % UserObject.DEFS,
                    "description": {"timestamp": "text", "statistic": "text", "time": "real"}
                },
                "DBORAWEV": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborawev)s select * from dborawev" % UserObject.DEFS,
                    "description": {"timestamp": "text", "event": "text", "count": "real", "timeouts": "real", "time": "real" }
                },
                "DBORAWEB": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboraweb)s select * from dboraweb" % UserObject.DEFS,
                    "description": {"timestamp": "text", "event": "text", "count": "real", "timeouts": "real", "time": "real" }
                },
                "DBORAWEH": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboraweh)s select * from dboraweh" % UserObject.DEFS,
                    "description": {"timestamp": "text", "event": "text", "bucket": "text", "count": "real"}
                },
                "DBORASQC": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqc)s select * from dborasqc" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "cpu": "real", "elapsed": "real", "gets": "real", "execs": "real"}
                },
                "DBORASQE": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqe)s select * from dborasqe" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "cpu": "real", "elapsed": "real", "reads": "real", "execs": "real"}
                },
                "DBORASQG": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqg)s select * from dborasqg" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "cpu": "real", "elapsed": "real", "gets": "real", "execs": "real"}
                },
                "DBORASQR": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqr)s select * from dborasqr" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "cpu": "real", "elapsed": "real", "reads": "real", "execs": "real"}
                },
                "DBORASQX": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqx)s select * from dborasqx" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "rows": "real", "execs": "real", "cpuperexec": "real", "elapsedperexec": "real"}
                },
                "DBORASQP": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqp)s select * from dborasqp" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "parses": "real", "execs": "real"}
                },
                "DBORASQM": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqm)s select * from dborasqm" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "sharedmem": "real", "execs": "real"}
                },
                "DBORASQV": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqv)s select * from dborasqv" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "versioncount": "real", "execs": "real"}
                },
                "DBORASQW": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasqw)s select * from dborasqw" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sqlid": "text", "cpu": "real", "elapsed": "real", "clusterwait": "real", "execs": "real"}
                },
                "DBORAREQ": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborareq)s select * from dborareq" % UserObject.DEFS,
                    "description": {"sqlid": "text", "request": "text"}
                },
                "DBORASTA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasta)s select * from dborasta" % UserObject.DEFS,
                    "description": {"timestamp": "text", "statistic": "text", "value": "real"}
                },
                "DBORADRV": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboradrv)s select * from dboradrv" % UserObject.DEFS,
                    "description": {"timestamp": "text", "statistic": "text", "value": "real"}
                },
                "DBORAOSS": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboraoss)s select * from dboraoss" % UserObject.DEFS,
                    "description": {"timestamp": "text", "statistic": "text", "value": "real"}
                },
                "DBORATBS": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboratbs)s select * from dboratbs" % UserObject.DEFS,
                    "description": {"timestamp": "text", "tablespace": "text", "reads": "real", "writes": "real", "busy": "real", "blocksperread": "real", "readtime": "real", "busytime": "real"}
                },
                "DBORAFIL": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborafil)s select * from dborafil" % UserObject.DEFS,
                    "description": {"timestamp": "text", "tablespace": "text", "file": "text", "reads": "real", "writes": "real", "busy": "real", "blocksperread": "real", "readtime": "real", "busytime": "real"}
                },
                "DBORAMDC": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboramdc)s select * from dboramdc" % UserObject.DEFS,
                    "description": {"timestamp": "text", "component": "text", "operation": "text", "size": "real", "vmin": "real", "vmax": "real", "opcount": "real"}
                },
                "DBORABUF": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborabuf)s select * from dborabuf" % UserObject.DEFS,
                    "description": {"timestamp": "text", "bufpool": "text", "gets": "real", "reads": "real", "writes": "real", "freewaits": "real", "writecompletewaits": "real", "busywaits": "real"}
                },
                "DBORAENQ": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboraenq)s select * from dboraenq" % UserObject.DEFS,
                    "description": {"timestamp": "text", "enqueue": "text", "requests": "real", "succgets": "real", "failedgets": "real", "waits": "real", "avgwait": "real"}
                },
                "DBORALAW": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboralaw)s select * from dboralaw" % UserObject.DEFS,
                    "description": {"timestamp": "text", "latch": "text", "wait": "real"}
                },
                "DBORALAT": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboralat)s select * from dboralat" % UserObject.DEFS,
                    "description": {"timestamp": "text", "latch": "text", "gets": "real", "misses": "real", "sleeps": "real"}
                },
                "DBORALIB": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboralib)s select * from dboralib" % UserObject.DEFS,
                    "description": {"timestamp": "text", "item": "text", "gets": "real", "pins": "real", "reloads": "real", "invalidations": "real"}
                },
                "DBORASGA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasga)s select * from dborasga" % UserObject.DEFS,
                    "description": {"timestamp": "text", "pool": "text", "name": "text", "size": "real"}
                },
                "DBORAPRM": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboraprm)s select * from dboraprm" % UserObject.DEFS,
                    "description": {"timestamp": "text", "parameter": "text", "value": "text"}
                },
                "DBORASGLR": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasglr)s select * from dborasglr" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "gets": "real"}
                },
                "DBORASGPR": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgpr)s select * from dborasgpr" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "reads": "real"}
                },
                "DBORASGRLW": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgrlw)s select * from dborasgrlw" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "waits": "real"}
                },
                "DBORASGIW": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgiw)s select * from dborasgiw" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "waits": "real"}
                },
                "DBORASGBBW": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgbbw)s select * from dborasgbbw" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "waits": "real"}
                },
                "DBORASGGCBB": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasggcbb)s select * from dborasggcbb" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "waits": "real"}
                },
                "DBORASGCRBR": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgcrbr)s select * from dborasgcrbr" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "blocks": "real"}
                },
                "DBORASGCBR": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgcbr)s select * from dborasgcbr" % UserObject.DEFS,
                    "description": {"timestamp": "text", "owner": "text", "tablespace": "text", "object": "text", "subobject": "text", "objtype": "text", "blocks": "real"}
                },
                "DBORAPGA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborapga)s select * from dborapga" % UserObject.DEFS,
                    "description": {"timestamp": "text", "aggrtarget": "real", "autotarget": "real", "memalloc": "real", "memused": "real"}
                },
                "DBORAPGC": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborapgc)s select * from dborapgc" % UserObject.DEFS,
                    "description": {"timestamp": "text", "highoptimal": "text", "execs0": "real", "execs1": "real", "execs2": "real"}
                },
                "DBORABPA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborabpa)s select * from dborabpa" % UserObject.DEFS,
                    "description": {"timestamp": "text", "bufpool": "text", "sizefactor": "text", "estphysreadsfactor": "real"}
                },
                "DBORAPMA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborapma)s select * from dborapma" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sizefactor": "text", "estextrabytesrw": "real", "estoveralloc": "real"}
                },
                "DBORASPA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dboraspa)s select * from dboraspa" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sizefactor": "text", "estloadtimefctr": "real"}
                },
                "DBORASGAA": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(masterlist)s, %(deltas)s, %(validdeltas)s, %(dborasgaa)s select * from dborasgaa" % UserObject.DEFS,
                    "description": {"timestamp": "text", "sizefactor": "text", "estphysicalreads": "real"}
                },
                "ORAHAS": {
                    "request": "with %(iname)s, %(mindate)s, %(maxdate)s, %(orahas)s select * from orahas" % UserObject.DEFS,
                    "description": {"timestamp": "text", "kairos_count": "bigint", "sql_id": "text", "sample_id": "text", "session_id": "text", "session_serial": "text", "user_id": "text", "sql_child_number": "text", "sql_plan_hash_value": "text", "force_matching_signature": "text", "sql_opcode": "text", "service_hash": "text", "session_type": "text", "session_state": "text", "qc_session_id": "text", "qc_instance_id": "text", "blocking_session": "text", "blocking_session_status": "text", "blocking_session_serial": "text", "event": "text", "event_id": "text", "seq": "text", "p1": "text", "p1text": "text", "p2": "text", "p2text": "text", "p3": "text", "p3text": "text", "wait_class": "text", "wait_class_id": "text", "wait_time": "real", "time_waited": "real", "xid": "text", "current_obj": "text", "current_file": "text", "current_block": "text", "program": "text", "module": "text", "action": "text", "client_id": "text", "blocking_hangchain_info": "text", "blocking_inst_id": "text", "capture_overhead": "text", "consumer_group_id": "text", "current_row": "text", "delta_interconnect_io_bytes": "real", "delta_read_io_bytes": "real", "delta_read_io_requests": "real", "delta_time": "real", "delta_write_io_bytes": "real", "delta_write_io_requests": "real", "ecid": "text", "flags": "text", "in_bind": "text", "in_connection_mgmt": "text", "in_cursor_close": "text", "in_hard_parse": "text", "in_java_execution": "text", "in_parse": "text", "in_plsql_compilation": "text", "in_plsql_execution": "text", "in_plsql_rpc": "text", "in_sequence_load": "text", "in_sql_execution": "text", "is_captured": "text", "is_replayed": "text", "is_sqlid_current": "text", "machine": "text", "pga_allocated": "real", "plsql_entry_object_id": "text", "plsql_entry_subprogram_id": "text", "plsql_object_id": "text", "plsql_subprogram_id": "text", "port": "text", "qc_session_serial": "text", "remote_instance": "text", "replay_overhead": "text", "sql_exec_id": "text", "sql_exec_start": "text", "sql_opname": "text", "sql_plan_line_id": "text", "sql_plan_operation": "text", "sql_plan_options": "text","temp_space_allocated": "real", "time_model": "text", "tm_delta_cpu_time": "real", "tm_delta_db_time": "real", "tm_delta_time": "real", "top_level_call": "text", "top_level_call_name": "text", "top_level_sql_id": "text", "top_level_sql_opcode": "text", "dbreplay_file_id": "text", "dbreplay_call_counter": "text"},
                },
                "ORAHQT": {
                    "request": "with %(orahqt)s select * from orahqt" % UserObject.DEFS,
                    "description": {"sql_id": "text", "sql_text": "text"}
                },
            },
        }
        super(UserObject, s).__init__(**object)
