class UserObject(dict):
    def __init__(s):
        object = {
            "type": "color",
            "id": "COLORS",
            "colors": {
                "CDB$ROOT": "black",
                "session logical reads": "darkgreen",
                "physical reads": "red",
                "redo size": "blue",
                "DB CPU": "yellow",
                "on cpu": "yellow",
                "cpu": "yellow",
                "CPU used by this session": "yellow",
                "elapsed": "gray",
                "Gets": "darkgreen",
                "Reads": "red",
                "Executions": "blue",
                "Rows": "brown",
                "Application": "orange",
                "User I/O": "pink",
                "Cluster": "purple",
                "Concurrency": "silver",
                "USER_TIME": "yellow",
                "usr": "yellow",
                "SYS_TIME": "orange",
                "sys": "orange",
                "NUM_CPUS": "red",
                "hit ratio": "red",
                "average time (ms)": "red",
                "number of operations/sec": "darkgreen",
                "number of timeouts/sec": "blue",
                "One pass execs": "orange",
                "Multi pass execs": "red",
                "user transactions": "red",
                "Memory other allocated": "lightgray",
                "Memory allocated": "yellow",
                "PGA aggregate target": "green",
                "Workarea (Manual + auto) allocated": "pink",
                "LOAD": "blue",
                "Run queue": "blue",
                "Swap queue": "pink",
                "IOWAIT_TIME": "darkgreen",
                "DB time": "gray",
                "Wait Events": "gray",
                "waiting": "gray",
                "user commits": "red",
                "user rollbacks": "#4baa25",
                "poolCPUs": "red",
                "virtualCPUs": "darkgreen",
                "Poolidle": "blue",
                "PhysicalCPU": "gray",
                "entitled": "orange",
                "EC_User%": "yellow",
                "EC_Idle%": "green",
                "EC_Sys%": "orange",
                "EC_Wait%": "blue",
                "VP_User%": "yellow",
                "VP_Idle%": "green",
                "VP_Sys%": "orange",
                "VP_Wait%": "blue",
                "Runnable": "gray",
                "Read MB/s": "red",
                "Write MB/s": "blue",
                "Busy rate %": "darkgreen",
                "All reports": "red",
                "All requests": "red",
                "All users": "red",
                "Response time": "blue",
            }
        }
        super(UserObject, s).__init__(**object)
